'$schema' = "https://schema.tauri.app/config/2"
productName = "poleshift"
version = "0.1.10"
identifier = "io.icarai.poleshift"

[build]
beforeDevCommand = "npm run dev"
devUrl = "http://localhost:1420"
beforeBuildCommand = "npm run build"
frontendDist = "../dist"

[app]
withGlobalTauri = true

[app.security]

[[app.windows]]
title = "poleshift"
width = 1_920
height = 1_080
visible = false
label = "main"

[[app.windows]]
title = "Initializing poleshift"
width = 800
height = 800
url = "/splashscreen"
label = "splashscreen"
decorations = false

[bundle]
active = true
targets = "all"
createUpdaterArtifacts = true
category = "Utility"
resources = [ "resources/taxdb_config.toml" ]
copyright = "IcarAI LLC 2025"
licenseFile = "../LICENSE"
publisher = "IcarAI LLC"
shortDescription = "Research application"

icon = [
    "icons/32x32.png",
    "icons/128x128.png",
    "icons/128x128@2x.png",
    "icons/icon.icns",
    "icons/icon.ico"
]

[bundle.macOS]
minimumSystemVersion = "12.0"

[bundle.iOS]
developmentTeam = "HZ64UH7RCV"

[[bundle.fileAssociations]]
ext = [ "fastq" ]
mimeType = "text/plain"
name = "fastqsanger"
role = "Editor"

[plugins.updater]
active = true
endpoints = [
    "https://cdn.crabnebula.app/update/icarai/poleshift/{{target}}-{{arch}}/{{current_version}}"
]
dialog = true
pubkey = "dW50cnVzdGVkIGNvbW1lbnQ6IG1pbmlzaWduIHB1YmxpYyBrZXk6IDFFNTVGMzc4OTdERTA4NjQKUldSa0NONlhlUE5WSGc2TDNtY3RBQlg5MG5wQ2FGL1dtZGV3Z3dRcW03RG5lV3VOSGs3QmNKMnQK"

[plugins.deep-link.desktop]
schemes = [ "tauri", "poleshift" ]
