name: Tauri v2 Build Test

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CN_APPLICATION: "icarai/poleshift"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest-l]

    env:
      TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
      TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
      APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
      APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
      APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      VITE_SUPABASE_URL: ${{secrets.VITE_SUPABASE_URL}}
      VITE_SUPABASE_ANON_KEY: ${{secrets.VITE_SUPABASE_ANON_KEY}}
      VITE_SUPABASE_JWT: ${{secrets.VITE_SUPABASE_JWT}}
      VITE_AYD_API_KEY: ${{secrets.VITE_AYD_API_KEY}}

    steps:
      - run: echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" | Out-File -FilePath $env:GITHUB_ENV -Append
        if: runner.os == 'Windows'
      - run: vcpkg install openssl:x64-windows-static-md
        if: runner.os == 'Windows'

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Checkout LFS objects
        run: |
          git config --global --add safe.directory /home/nikothomas/actions-runner/_work/poleshift/poleshift
          git lfs checkout

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: true

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'pnpm'

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.os == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Rust Cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './apps/poleshift-app/src-tauri -> target'

      - name: Install Dependencies on Ubuntu
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.1 libwebkit2gtk-4.1-dev libayatana-appindicator3-dev librsvg2-dev patchelf

      - name: Add Rust Targets for macOS
        if: matrix.os == 'macos-latest'
        run: |
          rustup target add x86_64-apple-darwin aarch64-apple-darwin

      - name: Install Node Modules
        run: pnpm install

      - name: Build Tauri Application
        shell: bash
        run: |
          if [ "${{ matrix.os }}" == "macos-latest" ]; then
            pnpm run build --target aarch64-apple-darwin
          elif [ "${{ matrix.os }}" == "windows-latest-l" ]; then
            pnpm run build --verbose
          else
            pnpm run build --verbose --bundles appimage deb
          fi
        working-directory: ./apps/poleshift-app
        env:
          NODE_OPTIONS: ${{ matrix.os == 'macos-latest' && '--max-old-space-size=8192' || '' }}